import dynamic from "next/dynamic"
import "./globals.css"
import type { Metadata } from "next"
import { Cinzel, Open_Sans } from "next/font/google"
import { ThemeToggle } from "@/components/ThemeToggle"
import { cn } from "@/utils"
import { Navigation } from "@/components/Navigation"
import { Footer } from "@/components/Footer"

const ThemeProvider = dynamic(() => import("@/components/theme-provider"), {
  ssr: false,
})

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-primary",
  weight: ["400", "500", "600", "700", "900"],
})

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "Movie World",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          openSans.variable,
          cinzel.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Navigation />
          {children}
          <Footer />
          <div className="container fixed bottom-0 left-0 z-50 mb-5">
            <ThemeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
